export const AI_IDEAS_BANK_SHORTS = [
  // Niche A: Dark Psychology & Wealth Mindset (01–25)
  "The psychological trick casinos use to make you lose track of time.",
  "The 'Decoy Effect': How fast-food chains force you to buy the large size.",
  "Why billionaires buy the exact same clothes every single day.",
  "The dark reason credit cards are made of heavy metal now.",
  "The 'Red Car' test that proves your brain is ignoring opportunities.",
  "The psychological loop behind why Tik Tok is so addictive.",
  "How supermarkets trick your brain into walking slower to spend more.",
  "Why rich people never say 'I can\\'t afford it.'",
  "The 72-hour rule that will instantly stop your impulse spending.",
  "The hidden cost of 'Buy Now, Pay Later' apps they don\\'t want you to calculate.",
  "How gym memberships rely on 80% of people quitting by February.",
  "The 'Sunk Cost Fallacy' keeping you trapped in a bad habit.",
  "The dark side of the lottery: What happens 5 years after winning.",
  "Why cheap products end up costing you 3x more over time.",
  "How streaming platforms use auto-play to steal your time.",
  "The 'Scarcity Principle': How online stores force you to buy right now.",
  "Why the ultra-wealthy rent luxury items instead of buying them.",
  "The psychology of a discount: Why 'Was $100, Now $20' works flawlessly.",
  "How your phone’s dark mode might be affecting your spending habits.",
  "The 'Diderot Effect': Why buying one new thing makes you buy ten more.",
  "Why real millionaires drive boring, ordinary cars.",
  "The 1-minute rule that stops stress spending instantly.",
  "The psychological reason menu items don’t use dollar signs ($).",
  "How free trials trap your brain into paying indefinitely.",
  "The unspoken rule of wealth: Shifting from a consumer to a producer mindset.",

  // Niche B: Unbelievable Animal & Nature Facts (26–50)
  "The shrimp that punches so hard it boils the surrounding water.",
  "Why the immortal jellyfish can technically live forever.",
  "The terrifying sound a blue whale makes that can kill a human.",
  "How crows remember human faces and hold grudges for years.",
  "The hidden fungal network underneath forests that acts like the internet.",
  "Why octopuses have three hearts and blue blood.",
  "The insect that survives being frozen solid all winter.",
  "How bats navigate pitch black darkness using their mouths.",
  "The terrifying truth about how fast a Hippo can actually run.",
  "Why chameleons don't change color just to blend in.",
  "The bird that can fly for ten months straight without landing once.",
  "How ants create living bridges using only their bodies.",
  "The deep-sea fish that generates its own glowing light.",
  "Why standard honey never spoils, even after thousands of years.",
  "The incredible defense mechanism of the horned lizard.",
  "How trees communicate warnings to each other when under attack.",
  "The terrifying speed of a peregrine falcon’s hunting dive.",
  "Why cats always land on their feet: The physics explained.",
  "The bizarre reason sloths only poop once a week.",
  "How regular pigeons can find their way home from thousands of miles away.",
  "The terrifying creature living at the very bottom of the Mariana Trench.",
  "Why sharks are older than trees and Saturn's rings.",
  "The microscopic water bear that can survive the vacuum of space.",
  "How an owl flies in absolute, dead silence.",
  "The plant that eats meat: Inside the Venus Flytrap.",

  // Niche C: Mind-Blowing Tech & AI Hacks (51–75)
  "The secret Google search trick to find free textbook PDFs.",
  "How to use an AI prompt to summarize a 3-hour video in 5 seconds.",
  "The hidden iPhone setting that stops apps from tracking your moves.",
  "How to turn any website into a clean, ad-free PDF instantly.",
  "The AI tool that writes professional emails in your exact voice.",
  "How to check if your personal email has been leaked on the dark web.",
  "The secret key combination to instantly recover a closed browser tab.",
  "How to use AI to generate a complete PowerPoint presentation in 60 seconds.",
  "The hidden setting that instantly makes your Windows PC run faster.",
  "How to create a completely custom font using your own handwriting.",
  "The secret site that shows you alternative free software for expensive apps.",
  "How to bypass a paywall on news sites legally.",
  "The AI prompt that turns a messy voice note into an organized essay.",
  "How to look directly at a webcam while reading a script using AI.",
  "The hidden map inside your phone that tracks everywhere you go.",
  "How to generate a custom logo for a business in under two minutes.",
  "The keyboard shortcut that instantly locks your computer when you walk away.",
  "How to clean up low-resolution photos using free AI upscalers.",
  "The secret email trick to see exactly who sold your data.",
  "How to use AI to translate your video into any language with perfect lip-syncing.",
  "The hidden setting that stops WhatsApp from saving junk media to your gallery.",
  "How to auto-transcribe a long audio file completely free.",
  "The AI tool that builds a working landing page in under three minutes.",
  "How to find out exactly what Google thinks your interests are for ads.",
  "The ultimate prompt to make ChatGPT act like an elite business coach.",

  // Niche D: Historical Paradoxes & Tech Secrets (76–100)
  "The historical event that caused a whole city to dance themselves to death.",
  "Why the ancient Romans used urine as mouthwash.",
  "The bizarre war fought over a single wooden bucket.",
  "How a typo in a cookbook led people to believe spinach had 10x more iron.",
  "The shortest war in human history that lasted less than 40 minutes.",
  "Why standard clock faces use the Roman numeral IIII instead of IV.",
  "The real reason the Leaning Tower of Pisa hasn’t fallen over yet.",
  "The ancient Greek machine that predicted eclipses 2,000 years ago.",
  "How the color purple became so expensive only kings could wear it.",
  "The real reason bubble wrap was originally invented.",
  "Why the government intentionally destroyed millions of pounds of cheese.",
  "The true story of the man who survived both atomic bomb blasts.",
  "How a single missing key caused the Titanic to hit the iceberg.",
  "The bizarre ancient custom of putting pets on trial in real courtrooms.",
  "Why paper money isn’t actually made of wood paper.",
  "The historical mystery of the colony that vanished without a trace.",
  "How a simple mold outbreak led to the greatest medical discovery ever.",
  "The ancient empire that defeated enemies using cats as shields.",
  "Why the chainsaw was originally invented (it wasn't for wood).",
  "The strange reason the dynamic 'QWERTY' keyboard layout was built to slow you down.",
  "The real origin of the phrase 'saved by the bell.'",
  "How a basic radar machine accidentally invented the microwave.",
  "The bizarre history of the Tulip crash that broke an entire country's economy.",
  "Why ancient statues have broken noses (it wasn't an accident).",
  "The bizarre mystery of the voynich manuscript that no one can read."
];

export const AI_IDEAS_BANK_LONGS = [
  // Niche A: Business Case Studies & Rise/Fall Documentaries (01–25)
  "The Rise and Tragic Fall of Blockbuster: The $50 Million Mistake.",
  "How Red Bull Sold a 25-Cent Drink for $3 and Built a Sports Empire.",
  "The Dumbest Business Decisions Ever Made: The Story of New Coke.",
  "How LEGO Went from Bankruptcy to the World's Biggest Toy Company.",
  "The Rise and Fall of BlackBerry: How iPhone Killed a Giant.",
  "How IKEA Strategically Brainwashes You into Buying Things You Don't Need.",
  "The Untold Story of Kodak: How the Inventors of Digital Film Ruined Themselves.",
  "How Nintendo Survived for 130 Years (Before Video Games Even Existed).",
  "The Collapse of WeWork: Inside a $47 Billion Illusion.",
  "How Costco Makes Millions by Intentionally Losing Money on Rotisserie Chickens.",
  "The Rise and Fall of Toys 'R' Us: The Real Reason It Disappeared.",
  "How Amazon Web Services (AWS) Secretly Funds the Entire Internet.",
  "The Rise and Fall of MySpace: The Mistake That Handed the Internet to Facebook.",
  "How Netflix Defeated Hollywood and Changed Television Forever.",
  "The Destruction of Yahoo: How a Tech Giant Turned Down Buying Google.",
  "The Monopoly Strategy: How Luxottica Secretly Owns Almost Every Sunglasses Brand.",
  "How Zara Rebuilt the Entire Fashion Industry in Less Than 15 Days.",
  "The Rise and Fall of Nokia: The Story of the Unkillable Phone Company.",
  "How Monster Energy Fought Red Bull and Captured a Billion-Dollar Market.",
  "The Collapse of Enron: The Corporate Scam That Shocked the Global Economy.",
  "How Spotify Conquered the Music Industry and Made Piracy Obsolete.",
  "The Rise and Fall of HTC: The Tragic Disappearance of a Smartphone Pioneer.",
  "How McDonald’s is Secretly a Real Estate Company, Not a Fast Food Chain.",
  "The Decline of Sears: How America’s Biggest Retailer Destroyed Itself from Within.",
  "How GoPro Created a Brand Empire and Then Ran Out of Things to Shoot.",

  // Niche B: Personal Finance & Macroeconomics Explained (26–50)
  "How Money is Created Out of Thin Air: The Fractional Reserve Banking System.",
  "The Real Reason the Middle Class is Disappearing Across the World.",
  "How the Ultra-Wealthy Legally Avoid Paying Income Tax Using Debt.",
  "The Silent Thief: How Inflation Destroys Your Savings Every Single Day.",
  "The Compound Interest Trap: How to Make Time Work for You, Not Banks.",
  "The 2008 Housing Crash Explained: How Greed Melted the Global System.",
  "Why the US Dollar Rules the World: The Deep History of the Petro-Dollar.",
  "How the Global Shipping Container Shortage Instantly Alters the Cost of Everything.",
  "The Economic Strategy of Switzerland: How a Small Country Became the World's Vault.",
  "The Truth About the 401(k): Is It a Retirement Plan or a Corporate Trap?",
  "How Credit Scores are Calculated and the Secret Matrix to Gamify Them.",
  "The Economic Illusion of Hyperinflation: When Printing Money Makes You Poorer.",
  "Why Real Estate is the Ultimate Wealth Generator for Everyday People.",
  "The Psychology of Hyper-Consumers: Why People Spend Money They Don't Have.",
  "How Credit Card Companies Make Billions Off People Who Pay On Time.",
  "The Index Fund Strategy: How to Out-Invest 90% of Wall Street Professionals.",
  "The Micro-Economics of Coffee: Why a Starbucks Latte Costs What It Does.",
  "How Short-Selling Works: How Wall Street Traders Profit When Companies Fail.",
  "The Economic Impact of an Aging Population: The Global Crisis Ahead.",
  "Why Fast Food is No Longer Cheap: The Real Math Behind Menu Inflation.",
  "The Financial Freedom Formula: The Step-by-Step Logic of the FIRE Movement.",
  "How Student Loan Debt Became a Multitrillion-Dollar Crisis.",
  "The Economics of Automation: Will AI Create Wealth or Mass Unemployment?",
  "Why De-Dollarization is Trending: Are Countries Giving Up on the US Dollar?",
  "The Wealth Cycle: How Money Moves Between the Poor, Middle Class, and Rich.",

  // Niche C: Geopolitics & Mega-Engineering Documentaries (51–75)
  "The Geopolitics of Semiconductors: Why a Tiny Island Holds the Global Tech Key.",
  "The Panama Canal Expansion: The Engineering Masterpiece Changing Trade.",
  "How China Built a Global Network of Ports: The Belt and Road Initiative.",
  "The Strategic Importance of the Strait of Malacca: The Chokepoint of World Commerce.",
  "The Engineering Behind the Burj Khalifa: How to Build a Mile Into the Sky.",
  "The Geopolitical Battle for the Arctic: The Fight for New Ocean Shipping Lanes.",
  "How the Netherlands Beats the Ocean: The Massive Delta Works System.",
  "The Global Water Crisis: The Looming War Over Earth's Most Crucial Resource.",
  "The Chunnel Engineering Marvel: How Britain and France Connected Underwater.",
  "The Lithium Gold Rush: The Geopolitical War to Control Electric Vehicle Batteries.",
  "How the Interstate Highway System Fundamentally Restructured the US Economy.",
  "The Megacity Boom: How Tokyo Built the Safest, Most Efficient Metro System.",
  "The Strategy of Direct Trade Routes: How the Suez Canal Saves Billions in Travel.",
  "The Engineering of the Three Gorges Dam: The Structure That Slowed Earth's Rotation.",
  "The Geopolitical Chessboard of Oil Pipelines: How Energy Defines Borders.",
  "The Mega-Port Architecture of Rotterdam: The Gatekeeper of European Commerce.",
  "How Singapore Transformed from a Poor Island to a Wealthy Global Hub.",
  "The Deep Sea Internet Cable Network: The Vulnerable Lines Keeping the World Connected.",
  "The Engineering Marvel of the Simplon Tunnel: Piercing the Heart of the Alps.",
  "The Economic Power of Sub-Saharan Infrastructure: The Future Trade Giants.",
  "The Geopolitics of Space Mining: The New Frontier for Trillion-Dollar Materials.",
  "How the Kansai Airport Was Built entirely on a Sinking Artificial Island.",
  "The Strategic Control of Rare Earth Minerals: Who Dominates Global Manufacturing?",
  "The Mega-Bridge Projects of China: Engineering Links Across Vast Oceans.",
  "The Geopolitical Reality of Food Security: How Countries Import Survival.",

  // Niche D: AI, Automation & Emerging Tech Futures (76–100)
  "The Race for Artificial General Intelligence (AGI): Who is Leading the Future?",
  "How Quantum Computing Will Instantly Break Modern Internet Encryption.",
  "The Automation Shift: The Industries Most Vulnerable to Advanced Software.",
  "The Future of Autonomous Transport: When Will Self-Driving Semis Rule Highways?",
  "How Algorithmic Trading Engines Completely Manage the Modern Stock Market.",
  "The Rise of No-Code Automation: How Small Teams Build Empires Using Logic Tools.",
  "The Dark Web Economy: The Technical Reality of Decentralized Black Markets.",
  "The Future of Renewable Storage: The Technology Needed Beyond Lithium-Ion.",
  "How AI Predictive Models are Rewriting the Medical Diagnostic Industry.",
  "The Decentralized Cloud: How Web3 Architecture Seeks to Challenge Big Tech.",
  "The Technical Evolution of CGI: From Simple Lines to Hyper-Realistic Virtual Worlds.",
  "The Tech Behind Modern Drones: How Mesh Networks Coordinate Hundreds of Aircraft.",
  "The Smart Grid Evolution: How Software Manages Nation-Scale Power Systems.",
  "The Mechanics of Deepfakes: The Technical Reality of Digital Manipulation.",
  "The Rise of Synthetic Media: How AI is Restructuring the Creator Economy.",
  "The Technology of Longevity: The Science Attempting to Reverse Cellular Aging.",
  "The Architecture of LLMs: How Large Language Models Actually Process Text.",
  "The Evolution of Wearable Tech: From Basic Step Counters to Neural Interface Bands.",
  "How Cybersecurity Automation Defends Networks from Thousands of Bot Attacks per Second.",
  "The Clean Energy Tech Race: The Mechanics Behind Advanced Nuclear Fusion Experiments.",
  "The Economics of the App Store Ecosystem: The Tech Tax Keeping Developers Trapped.",
  "The Technology Behind Satellite Internet: The Mega-Constellations Encircling Earth.",
  "The Rise of Digital Twins: How Cities and Factories are Simulated in Virtual Reality.",
  "The Technical Architecture of Modern Search Engines: Moving Beyond Text to Concepts.",
  "The Final Tech Frontier: A Comprehensive Look at Brain-Computer Interfaces."
];
